apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webshot-worker
  labels:
    app: webshot-worker
    track: stable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webshot-worker
        track: stable
    spec:
      containers:
        - name: webshot-worker
          image: rosskukulinski/webshot-worker:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            timeoutSeconds: 5
