apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
    - nodePort: 30000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: helloworld
  type: LoadBalancer
